- name: Ensure <Role_vars_file> exists with ssh_hosts
  local_action:
    module: lineinfile
    args:
      path: "{{ Role_vars_file }}"
      line: "ssh_hosts:"
      create: yes
      state: present

- name: Check if VM is in the <Role_vars_file>
  set_fact:
    _vm_exists: "{{ ssh_hosts | selectattr('name', 'equalto', vm_name) | list | length > 0 }}"
  vars:
    ssh_hosts: "{{ lookup('file', Role_vars_file).ssh_hosts | from_yaml | default([]) }}"

- name: Append VM to the list if not exists
  local_action:
    module: lineinfile
    args:
      path: "{{ Role_vars_file }}"
      insertafter: "ssh_hosts:"
      line: "{{ '  - {name: %s, ip: %s }' | format(vm_name, vm_ip) }}"
  when: not _vm_exists
