- name: Check <host_vars_file> exists
  local_action:
    module: stat
    args:
      path: "{{ host_vars_file }}"
  register: _result_stat

- name: Create <host_vars_file>
  block:
  - name: Create host_vars_file directory
    local_action:
      module: file
      args:
        path: "{{ host_vars_file | dirname }}"
        state: directory

  - name: Generate <host_vars_file>
    local_action:
      module: blockinfile
      args:
        path: "{{ host_vars_file }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR vm info"
        block: |
          ansible_user: "{{ User_name }}"
          vm:
            name: "{{ vm_name }}"
            id: "{{ vm_id }}"
            ip: "{{ vm_ip }}"
            ssh_user: "{{ User_name }}"
        create: yes
  when: not _result_stat.stat.exists
