- name: Show server
  uri:
    url: "{{ URL.COMPUTE }}/servers/{{ vm_id }}"
    method: GET
    headers:
      X-Auth-Token: "{{ Xauth_token }}"
    validate_certs: no
  register: _response

- name: Print response
  debug:
    var: _response.json.server

- name: Set _vm_ip
  set_fact:
    _vm_ip: "{{ _response.json.server.addresses[network_name][0].addr }}"
