- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set _xauth_token
      include_role:
        name: api
        tasks_from: set_token
  vars:
    _vm_params_file: "{{ playbook_dir }}/vm_params.yml"
  tasks:
    - name: Include <_vm_params_file> to vm_params
      include_vars:
        file: "{{ _vm_params_file }}"
        name: _tmp

    - name: Define vm_group
      add_host:
        name: "{{ vm.VM_NAME }}"
        groups: vm_group
        VM_NAME: "{{ vm.VM_NAME }}"
        IMG_UUID: "{{ vm.IMG_UUID }}"
        FLV_UUID: "{{ vm.FLV_UUID }}"
        VOL_SIZE: "{{ vm.VOL_SIZE }}"
        USER_NAME: "{{ vm.USER_NAME }}"
      loop: "{{ _tmp.vm_params }}"
      loop_control:
        loop_var: vm
      when: vm.VM_NAME not in groups['all']


- hosts: vm_group
  gather_facts: no
  pre_tasks:
    - name: Set vars
      set_fact:
        _config_path: "/etc/ssh/ssh_config.d/{{ _project_name }}.conf"
        _role_vars_file: "{{ playbook_dir }}/roles/ssh/vars/main.yml"
        _host_vars_dir: "{{ playbook_dir }}/host_vars"
        _inventory_file: "{{ playbook_dir }}/hosts"
      vars:
        _project_name: "{{ playbook_dir.split('/')[-1] }}"
      run_once: yes
  tasks:
    - name: Execute create_server_tasks
      include_tasks:
        file: create_server_tasks.yml
        apply:
          delegate_to: localhost
      vars:
        Xauth_token: "{{ hostvars['localhost']['_xauth_token'] }}"
        Ansible_ssh_config: "{{ _config_path }}"
        Role_vars_file: "{{ _role_vars_file }}"
        Host_vars_dir: "{{ _host_vars_dir }}"
        Inventory_file: "{{ _inventory_file }}"
        Vm_name: "{{ VM_NAME }}"
        Img_uuid: "{{ IMG_UUID }}"
        Flv_uuid: "{{ FLV_UUID }}"
        Vol_size: "{{ VOL_SIZE }}"
        User_name: "{{ USER_NAME }}"
        Networks: "{{ NETWORKS }}"
        Key_name: "{{ KEY_NAME }}"
        Group_name: "{{ GROUP_NAME }}"
