- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set vars
      set_fact:
        _config_path: "/etc/ssh/ssh_config.d/{{ _project_name }}.conf"
      vars:
        _project_name: "{{ playbook_dir.split('/')[-1] }}"
  tasks:
    - name: Extract vm.ip from each host_var
      set_fact:
        ssh_hosts: "{{ groups['all'] | map('extract', hostvars, 'vm') }}"

    - name: Generate ssh config
      include_role:
        name: ssh
        tasks_from: create_ssh_config
      vars:
        Ansible_ssh_config: "{{ _config_path }}"
        Key_name: "{{ KEY_NAME }}"
