- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set _xauth_token
      include_role:
        name: api
        tasks_from: set_token
    - name: Set vars
      set_fact:
        _vm_date: "{{ 'vm_' + lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
        _host_vars_dir: "{{ playbook_dir }}/host_vars"
        _inventory_file: "{{ playbook_dir }}/hosts"
  vars:
    VM_NAME: "{{ _vm_date }}"
    IMG_UUID: <img_uuid>  # replace with image uuid
    FLV_UUID: <flv_uuid>  # replace with flavor uuid
    VOL_SIZE: <vol_size>  # replace with volume size
    USER_NAME: <user_name>  # replace with user name
  tasks:
    - name: Include deploy role
      include_role:
        name: deploy
        apply:
          delegate_to: localhost
      vars:
        Xauth_token: "{{ _xauth_token }}"
        Host_vars_dir: "{{ _host_vars_dir }}"
        Inventory_file: "{{ _inventory_file }}"
        Vm_name: "{{ VM_NAME }}"
        Img_uuid: "{{ IMG_UUID }}"
        Flv_uuid: "{{ FLV_UUID }}"
        Vol_size: "{{ VOL_SIZE }}"
        User_name: "{{ USER_NAME }}"
        Networks: "{{ NETWORKS }}"
        Key_name: "{{ KEY_NAME }}"
        Group_name: "{{ GROUP_NAME }}"
  post_tasks:
    - name: Prompt to run create_ssh_config
      debug:
        msg: |
          All tasks have completed.
          Please run the following command.
          ===
          ansible-playbook create_ssh_config.yml
          ===