- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for icmp
      wait_for_connection:
        timeout: 300

    - name: Wait for ssh
      wait_for:
        port: 22
        state: started
        timeout: 300
