- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set _xauth_token
      include_role:
        name: api
        tasks_from: set_token
  tasks:
    - name: Check VM_ID
      fail:
        msg: "VM_ID is not defined. Exiting..."
      when: VM_ID is undefined

    - name: Start server
      include_role:
        name: api
        tasks_from: start_server
      vars:
        Xauth_token: "{{ _xauth_token }}"
        Vm_id: "{{ VM_ID }}"
