- name: Delete Keypair
  uri:
    url: "{{ URL.COMPUTE }}/os-keypairs/{{ Key_name }}"
    method: DELETE
    headers:
      X-Auth-Token: "{{ xauth_token }}"
    status_code: [202, 204, 404]
    validate_certs: no
  register: _result_uri

- name: Check if the keypair was not found
  debug:
    msg: |
      The keypair: {{ Key_name }} was not found.
      Proceeding with the remaining tasks.
  when: _result_uri.status == 404
