- name: Get token
  uri:
    url: "{{ URL.IDENTITY }}/auth/tokens"
    method: POST
    body_format: json
    body:
      auth:
        identity:
          methods:
            - "password"
          password:
            user:
              id: "{{ AUTH.USER.ID }}"
              password: "{{ AUTH.USER.PASSWORD }}"
        scope:
          project:
            domain:
              id: "{{ AUTH.DOMAIN.ID }}"
            name: "{{ AUTH.PROJECT.NAME }}"
    status_code: 201
    validate_certs: no
  register: _response

- name: Set _xauth_token
  set_fact:
    _xauth_token: "{{ _response.x_subject_token }}"

- name: Print _xauth_token
  debug:
    var: _xauth_token
